
default: 
	g++ -std=c++2a -o Main. ../Main.cpp -I ../include/ 
	# x86_64-w64-mingw32-g++ -std=c++2a -o WinMain. ../Main.cpp -I ../include/ 
	x86_64-w64-mingw32-g++ -std=c++2a -o WinMain.exe ../Main.cpp -I ../include/ 


